version: '3'

networks:
  inception:


services:

  mariadb:
    container_name: mariadb
    # image: mariadb
    env_file:
      - .env
    networks:
      - inception
    build: requirements/mariadb
    expose:
      - 3306
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: unless-stopped

  wordpress:
    container_name: wordpress
    # image: wordpress
    env_file:
      - .env
    networks:
      - inception
    build: requirements/wordpress
    expose:
      - 9000
    volumes:
      - wordpress_data:/var/www/wordpress
    restart: unless-stopped
    depends_on:
      - mariadb

  nginx:
    container_name: nginx
    # image: nginx
    networks:
      - inception
    build: requirements/nginx
    ports:
      - 443:443
    volumes:
      - wordpress_data:/var/www/wordpress
    restart: unless-stopped
    depends_on:
      - wordpress

volumes:
  mariadb_data:
  wordpress_data:


