version: '3'

networks:
  inception:


volumes:
  db_volume:
    name: db_volume
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/cmeng/data/db_volume
  wp_volume:
    name: wp_volume
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/cmeng/data/wp_volume

services:

  mariadb:
    container_name: mariadb
    image: mariadb
    env_file:
      - .env
    networks:
      - inception
    build: requirements/mariadb
    expose:
      - 3306
    volumes:
      - db_volume:/var/lib/mysql
    restart: unless-stopped

  wordpress:
    container_name: wordpress
    image: wordpress
    env_file:
      - .env
    networks:
      - inception
    build: requirements/wordpress
    expose:
      - 9000
    volumes:
      - wp_volume:/var/www/html
    restart: unless-stopped
    depends_on:
      - mariadb

  nginx:
    container_name: nginx
    image: nginx
    networks:
      - inception
    build: requirements/nginx
    ports:
      - 443:443
    restart: unless-stopped
    depends_on:
      - wordpress
