version: '3'
networks:
  inception:


services:

  nginx:
    container_name: nginx
    image: nginx
    networks:
      - inception
    build: requirements/nginx
    ports:
      - 443:443
    # volumes:
    #   - ./requirements/nginx/conf:/etc/nginx/conf.d
    depends_on:
      - mariadb

  mariadb:
    container_name: mariadb
    image: mariadb
    env_file:
      - .env
    networks:
      - inception
    build: requirements/mariadb
    environment:
      - SQL_DATABASE=$${SQL_DATABASE}
      - SQL_USER=$${SQL_USER}
      - SQL_PASSWORD=$${SQL_PASSWORD}
    ports:
      - 3306:3306
    # volumes:
    #   - mariadb_data:/var/lib/mysql

    # volumes:
    #   mariadb_data:
