version: '3'

networks:
  inception:


volumes:
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/christianmeng/Documents/projects/inception/data/mariadb
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/christianmeng/Documents/projects/inception/data/wordpress

services:

  mariadb:
    container_name: mariadb
    image: mariadb
    env_file:
      - .env
    networks:
      - inception
    build: requirements/mariadb
    expose:
      - 3306
    volumes:
      - mariadb:/var/lib/mysql
    restart: unless-stopped

  # wordpress:
  #   container_name: wordpress
  #   image: wordpress
  #   env_file:
  #     - .env
  #   networks:
  #     - inception
  #   build: requirements/wordpress
  #   expose:
  #     - 9000
  #   volumes:
  #     - wordpress:/var/www/html
  #   restart: unless-stopped
  #   depends_on:
  #     - mariadb

  nginx:
    container_name: nginx
    image: nginx
    networks:
      - inception
    build: requirements/nginx
    ports:
      - 443:443
    restart: unless-stopped
    # depends_on:
    #   - wordpress

